### ISSUE TITLE
Error:"profile_image_url_https"

### ISSUE THREAD

**Issue by dishanisen** [euagendas/m3inference#33] opened 2022-05-13 20:39 UTC
I am getting the following error with m3twitter.transform_jsonl()
The data has been shared privately with Zijian Wang. 
<img width="1097" alt="Screenshot 2022-05-13 at 5 56 59 PM" src="https://user-images.githubusercontent.com/42896082/168386053-cb160413-32c4-4c3c-a7d3-d0b33e5aeae1.png">

**Comment by computermacgyver** [comment] 2022-05-13 21:02
Is your data from the v1.1 or v2 API @dishanisen ?

Currently only data in the v1.1 API format is supported. I think this may duplicate #31 , but would appreciate your confirmation of what version of the API the data came from.

**Comment by dishanisen** [comment] 2022-05-13 21:12
Hi,

I have the Academic Twitter API, so I do not exactly know if it's v1 or v2.

**Comment by computermacgyver** [comment] 2022-05-13 21:23
That is the v2 API. It was released after our project. I hope we'll extend the code to support data from it, but at the moment you would need to manually reform the data to the m3 input format.

I'm going to close this as a duplicate of #31 for now.

**Closed** 2022-05-13 21:23 UTC

**Comment by computermacgyver** [comment] 2022-05-13 21:25
Also to clarify, I mean that if you can transform the data to look the the examples in this file
https://github.com/euagendas/m3inference/blob/master/test/data.jsonl
then it will work. Unfortunately we don't have code to do that right now.
